services:
  # Asia / Oceana (Singapore fallback for Tokyo/Australia)
  - type: web
    name: zchat-cdn-sg
    env: node
    region: singapore
    plan: free
    rootDir: cdn
    buildCommand: npm install
    startCommand: npm start

  # Europe / Africa (Frankfurt fallback for London)
  - type: web
    name: zchat-cdn-fra
    env: node
    region: frankfurt
    plan: free
    rootDir: cdn
    buildCommand: npm install
    startCommand: npm start

  # US West / South America West (Oregon)
  - type: web
    name: zchat-cdn-oregon
    env: node
    region: oregon
    plan: free
    rootDir: cdn
    buildCommand: npm install
    startCommand: npm start

  # US East / South America East (Ohio & Virginia)
  - type: web
    name: zchat-cdn-ohio
    env: node
    region: ohio
    plan: free
    rootDir: cdn
    buildCommand: npm install
    startCommand: npm start
